config/routes.rb
ZombieTwitter::Application.routes.draw do
  resources :zombies do
    resources :tweets
  end

  get "pages/home"

  get "pages/sign_up"

  root :to => "pages#home"

  match '/sign_up' => 'pages#sign_up'

  match '/new_tweet' => 'tweets#new'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :zombie
	
	belongs_to :role
end

app/models/brain.rb
class Brain < ActiveRecord::Base
  attr_accessible :flavor, :status, :zombie_id

  belongs_to :zombie

end

app/models/role.rb
class Role < ActiveRecord::Base
	attr_accessible :title

	has_many :assignments

	has_many :zombies, through: :assignments
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :status, :zombie_id

  validates_presence_of :status, :zombie_id

  validates_length_of :status, :maximum => 140

  belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  after_save :decomp_change_notification, if: :decomp_changed?

  attr_accessible :graveyard, :name, :age, :rotting, :strength, :email

  has_many :tweets

  has_many :assignments

  has_many :roles, through: :assignments

  has_one :brain, dependent: :destroy
  
  before_save :make_rotting

  def make_rotting
  	if age > 20
  		self.rotting = true
  	end
  end

  private

  def decomp_change_notification
    ZombieMailer.decomp_change(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController

	 def new
    @brain = Brain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

	def create
	end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sign_up
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :get_zombie

  def get_zombie
    @zombie = Zombie.find(params[:zombie_id])
  end

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = @zombie.tweets

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = @zombie.tweets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = @zombie.tweets.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        flash[:success] = "Tweet created!"
        redirect_to [@zombie, @tweet]
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to [@zombie, @tweet], notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to [@zombie, @tweet], notice: 'Tweet was successfully destroyed' }
      format.json { head :no_content }
    end
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zombie Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Sign Up", "/sign_up", :confirm => "Are you sure?" %>

app/views/pages/sign_up.html.erb
<h1>Pages#sign_up</h1>
<p>Find me in app/views/pages/sign_up.html.erb</p>

app/views/tweets/_form.html.erb
<%= form_for([@zombie, @tweet]) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :zombie_id %><br />
    <%= f.number_field :zombie_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>


<%= link_to 'Back', zombie_tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets for 
  <%= @zombie.name %>
</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Zombie</th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.status %></td>
    <td><%= tweet.zombie.name %></td>
    <td><%= link_to 'Show', [@zombie, tweet] %></td>
    <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
    <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', zombie_tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @tweet.status %>
</p>

<p>
  <b>Zombie:</b>
  <%= @tweet.zombie_id %>
</p>


<%= link_to 'Edit', edit_zombie_tweet_path %> |
<%= link_to 'Back', zombie_tweets_path %>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :graveyard %><br />
    <%= f.text_field :graveyard %>
  </div>
    <div class="field">
    <%= f.label :age %><br />
    <%= f.radio_button :age, 25, checked: true %>25<br />
    <%= f.radio_button :age, 26 %>26<br />
    <%= f.radio_button :age, 27 %>27<br />
  </div>
  <div class="field">
    <%= f.label :strength %><br />
    Weak
    <%= f.range_field :strength, :in => 0..100, :step => '1' %>
    Strong
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Graveyard</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.name %></td>
    <td><%= zombie.graveyard %></td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>

<p>
  <b>Graveyard:</b>
  <%= @zombie.graveyard %>
</p>

<h3>Recent Tweets:</h3>

<table>
	<% @zombie.tweets.each do |tweet| %>
	  <tr>
	    <td><b><%= tweet.status %></b></td>
	  </tr>
	<% end %>
</table>

<h3>
	<%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>
</h3>



<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>